### ISSUE TITLE
My code is something like this. It occurs error this.saveToCache is not function. Can anyone help? thanks in advance.

### ISSUE THREAD

**Issue by whip8466** [Collaborne/iron-localstorage-behavior#1]
<link rel="import" href="../bower_components/polymer/polymer.html">
	<link rel="import" href="../bower_components/polymer/polymer-element.html">
	<link rel="import" href="shared-styles.html">

	<link rel="import" href="../bower_components/iron-localstorage-behavior/iron-localstorage-behavior.html">

	<dom-module id="my-app">
	    <template>
	        <paper-button on-click="_insertData">Add<paper-button>
	    </template>
	    <script>
	        class MyApp extends Polymer.Element {
	            static get is() { return 'my-app'; }
	             _insertData(){
	                var key = 123;
	                var value = Math.random();
	                this.saveToCache(key, value).then(() => {
	                    alert("Added");
	                });
	            }
	        }

	        window.customElements.define(MyApp.is, MyApp);
	    </script>
	</dom-module>

**Comment by ronnyroeller** [comment]
See the demo for how to add the behavior to a Polymer 1.0 element: https://github.com/Collaborne/iron-localstorage-behavior/blob/master/demo/simple-localstorage-element.html#L44

See here how to use Polymer 1.0 behaviors with Polymer 2.0 elements: https://www.polymer-project.org/2.0/docs/upgrade#mixins
